//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measurements.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"PUTVIEW /xy=1,1 /cxcy=-100,-75 /NO_DATASRC\"\r\n\r\n")]
        public string ShowGenie {
            get {
                return ((string)(this["ShowGenie"]));
            }
            set {
                this["ShowGenie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"ECHO OFF\"\r\n\"REXXFCTS\"\r\nCALL G2KENVMT\r\nIF RC <> 0 THEN EXIT\r\n\r\n")]
        public string StartStrings {
            get {
                return ((string)(this["StartStrings"]));
            }
            set {
                this["StartStrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"PVOPEN DET:\"detname\" /EXPAND\"\r\n")]
        public string addDetectors {
            get {
                return ((string)(this["addDetectors"]));
            }
            set {
                this["addDetectors"] = value;
            }
        }
    }
}
